### ISSUE TITLE
Cannot find module "cv2" Post-installation camera information

### ISSUE THREAD

**Issue by jacksonattwood** [Boltgolt/howdy-reports#7]
I keep on getting errors where it can't find module cv2

```
jackson@jackson-Inspiron-5379:~$ sudo howdy jackson add
Traceback (most recent call last):
  File "/lib/security/howdy/compare.py", line 11, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
Unknown error: 1
[sudo] password for jackson: 
Traceback (most recent call last):
  File "/usr/bin/howdy", line 42, in <module>
    import cli.add
  File "/lib/security/howdy/cli/add.py", line 9, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
```

Video devices [IR=1]
```
video0
video1
```
Lsusb output
```
    iConfiguration          4 USB Camera
      iFunction               5 Integrated Webcam
        wTerminalType      0x0201 Camera Sensor
      iFunction               6 Integrated Webcam
        wTerminalType      0x0201 Camera Sensor
```
Udevadm
```
E: ID_BUS=usb
E: ID_MODEL=Integrated_Webcam_HD
E: ID_MODEL_ENC=Integrated_Webcam_HD
E: ID_MODEL_ID=5696
E: ID_V4L_PRODUCT=Integrated_Webcam_HD: Integrate
E: ID_VENDOR_ID=0bda
```

**Comment by Boltgolt** [comment]
This is the wrong repository to report that, please take a look at [this comment](https://github.com/Boltgolt/howdy/issues/7#issuecomment-368305023) in the main repo.

**Comment by Boltgolt** [comment]
Yes, so have they. On some installations something goes wrong and cv2 doesn't get linked correctly. Please try that answer and if it doesn't work open a new issue there, this isn't the place for it.
